Import('env')

# Import common Darwin setttings
env.SConscript(['../SConscript'])

# Darwin x86 specific build settings
env.Append(CPPDEFINES=['QCC_CPU_X86'])

ccld = ['-mmacosx-version-min=10.5.4']
env.Append(CXXFLAGS=ccld)
env.Append(CFLAGS=ccld)
env.Append(LINKFLAGS=ccld)
