Import('env')

# Import common Darwin setttings
env.SConscript(['../SConscript'])

# Darwin x86 specific build settings
env.Append(CPPDEFINES=['QCC_CPU_X86'])

# Force 32-bit builds
ccld = ['-arch', 'i386', '-arch', 'x86_64', '-mmacosx-version-min=10.5.4']
env.Append(CXXFLAGS=ccld)
env.Append(CFLAGS=ccld)
env.Append(LINKFLAGS=ccld)
